---
title: "16SrRNA and Chemistry_Incubation"
author: "Laura Seidel"
date: "3/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(gplots))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggtree))
suppressPackageStartupMessages(library(ggord))
suppressPackageStartupMessages(library(SRS))
suppressPackageStartupMessages(library(Hmisc))
suppressPackageStartupMessages(library(lme4))
suppressPackageStartupMessages(library(stargazer))
suppressPackageStartupMessages(library(microshades))
suppressPackageStartupMessages(library(phyloseq))
suppressPackageStartupMessages(library(lattice))
suppressPackageStartupMessages(library(nlme))
suppressPackageStartupMessages(library(emmeans))
suppressPackageStartupMessages(library(ggiraphExtra))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(apeglm))
suppressPackageStartupMessages(library(zinbwave)) 
suppressPackageStartupMessages(library(scran))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(pscl))
suppressPackageStartupMessages(library(MASS))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(dotwhisker))

```

```{r tables}
##Meta data
meta <- read.csv("meta.csv", stringsAsFactors = FALSE)

##Phytoref sequences - to get rid of sequences which are not Cyanobacteria 
phyto <- read.csv("phytoref_results_BW_SED_incub_cyanos.csv", header=TRUE)

##Incubation study counts - BW & SED ASVs from the incubation study
counts <- read.table("16S/seqtab_final.txt",stringsAsFactors =FALSE, header=TRUE)%>% 
  gather(sample,count, 2:ncol(.))%>%
  filter(count > 0)
##Field Bottom water (BW) ASV counts 
countsFBW <- read.csv("BW_May_seqtab.csv", stringsAsFactors = FALSE)%>% 
  gather(sample,count, 2:ncol(.)) %>% 
  filter(count > 0)

#Field Sediment (SED) ASV counts
countsFSED <- read.csv("SED_May_seqtab.csv", stringsAsFactors = FALSE)%>%
  gather(sample, count, 2:ncol(.))%>%
  filter(count >0)

##Combine the counts (combine by rows)
counts_all <- rbind(counts, countsFBW, countsFSED)

##Used GTDB version 86
##Incubation study taxa tables
#Replace NA with Unclassified
taxa <- read.table("tax_final.txt",stringsAsFactors = FALSE, header=TRUE)%>%
        replace_na(list(Phylum="Unclassified"))%>%
        replace_na(list(Class="Unclassified"))%>%
        replace_na(list(Order="Unclassified"))%>%
        replace_na(list(Family="Unclassified"))%>%
        replace_na(list(Genus="Unclassified"))%>%
        replace_na(list(Species="Unclassified"))

##Field BW taxa tables
taxaFBW <- read.table("tax_final_MAY_BW.txt", stringsAsFactors =FALSE, header = TRUE)%>%
        replace_na(list(Phylum="Unclassified"))%>%
        replace_na(list(Class="Unclassified"))%>%
        replace_na(list(Order="Unclassified"))%>%
        replace_na(list(Family="Unclassified"))%>%
        replace_na(list(Genus="Unclassified"))%>%
        replace_na(list(Species="Unclassified"))


##Field SED taxa tables
taxaFSED <- read.table("tax_final_May_SED.txt", stringsAsFactors =FALSE, header = TRUE)%>%
        replace_na(list(Phylum="Unclassified"))%>%
        replace_na(list(Class="Unclassified"))%>%
        replace_na(list(Order="Unclassified"))%>%
        replace_na(list(Family="Unclassified"))%>%
        replace_na(list(Genus="Unclassified"))%>%
        replace_na(list(Species="Unclassified"))

##Combine all taxa tables (get rid of the duplicates)
taxa_all <- union(taxa, taxaFBW, taxaFSED)%>% 
 filter(Family != "Mitochondria") %>% 
  filter(Class  != "Chloroplast")%>%
  distinct(sequence,.keep_all = TRUE)


##Just keeps the duplicate sequences, which happened to be in the merged taxa table
taxa_dist <- union(taxa, taxaFBW, taxaFSED)%>% 
 filter(Family != "Mitochondria") %>% 
  filter(Class  != "Chloroplast")%>%
  distinct()


##Combine all tables into one big one
ALL <- counts_all%>% 
  left_join(meta, by="sample") %>% 
  left_join(taxa_all, by="sequence")%>% 
  filter(Family != "Mitochondria") %>% 
  filter(Class  != "Chloroplast")%>% 
  anti_join(phyto, by="sequence")

##Only BW
BW <- ALL %>% filter(format == "BW") 

##Only SED

SED <- ALL %>% filter(format =="PW")


##Bacterial production table

BP <- read.csv("BP_OKG_calculations_2203_corrected_Final.csv",stringsAsFactors =FALSE, header = TRUE)


```

```{r format tables}
##raw counts from both material BW and SED
countsRAW <- counts_all %>%  
  group_by(sample) %>% 
  # Filter to keep only rows from samples having at least 1000 counts
  filter(sum(count) >= 1000) %>% 
  dplyr::select(sequence, sample, count) %>% #select ISV, sample and count
  spread(sequence,count, fill= 0) %>% #wide format with sequence and count, filling gaps with 0
  remove_rownames() %>% #remove of row names
  column_to_rownames(var = "sample")


##Relative abundance (relab) and filter all counts under 1000 

##BW
BW<- BW %>%
  # Group by sample, to get access to the group wise sum of counts
  group_by(sample) %>% 
  # Filter to keep only rows from samples having at least 1000 counts
  filter(sum(count) >= 1000) %>% 
  # Since we have the data grouped, we can calculate the relative abundance here
  mutate(relab = count/sum(count)) %>%
  ungroup()

##SED
SED <- SED %>%
  group_by(sample) %>% 
  filter(sum(count) >= 1000) %>% 
  mutate(relab = count/sum(count)) %>%
  ungroup()

##Wide Format on counts##
##BW
widecountBW<- BW%>% 
  dplyr::select(sequence, sample, count) %>% 
  spread(sequence,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample")

##SED
widecountSED<- SED%>% 
  dplyr::select(sequence, sample, count) %>% 
  spread(sequence,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample")

##Wide format on relab##
##BW
widerelabBW<- BW%>% 
  dplyr::select(sequence, sample, relab) %>% 
  spread(sequence,relab, fill= 0) %>%
  remove_rownames() %>% 
  column_to_rownames(var = "sample")

##SED
widerelabSED<- SED%>% 
  dplyr::select(sequence, sample, relab) %>% 
  spread(sequence,relab, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample")
```

```{r bacterial production - Figure 2AB alternative}
#Figure 2 and Figure S6 for bacterial production have been generated with SigmaPlot
#below an alernative plot for Figure 2 A/B with plotly

# Make a surface plot with the heated bay data
BPsel <- BP %>% 
  dplyr::select(Time_1, bay, real_temp, ugC.L.d)%>%
  filter(!Time_1 %in% "Start")%>%
  filter(bay %in% "heated")

#make the values numeric
BPsel$ugC.L.d <- as.numeric(BPsel$ugC.L.d)

#use plotly to generate a figure
fig <- plot_ly(BPsel, x = ~real_temp, y = ~Time_1, z = ~ugC.L.d,  type="contour",  intensity = ~ugC.L.d, 
          color=~ugC.L.d,
           colors = colorRamp(c(
             rgb(153,255,255, max=255),
             rgb(0,0,255, max=255),
             rgb(0, 255, 0, max = 255),
             rgb(247,255,0, max = 255),
             rgb(255, 0, 0, max = 255),
             rgb(152,0,0, max=255)
           )),
           showscale = TRUE,
           autocontour = TRUE,
   contours = list(
    coloring = 'heatmap'
  )
  )

#plot the figure
fig

#save the figure as html
htmlwidgets::saveWidget(as_widget(fig), "fig_heatedbay_3D_BP_plotly.html")

#Control bay surface plot with plotly
BPselcon <- BP %>% 
  dplyr::select(Time_1, bay, real_temp, ugC.L.d)%>%
  filter(!Time_1 %in% "Start")%>%
  filter(!bay %in% "heated")

BPselcon$ugC.L.d <- as.numeric(BPselcon$ugC.L.d)

figcon <- plot_ly(BPselcon, x = ~real_temp, y = ~Time_1, z = ~ugC.L.d,  type="contour",  intensity = ~ugC.L.d,
 color=~ugC.L.d,
           colors = colorRamp(c(
             rgb(153,255,255, max=255),
             rgb(0,0,255, max=255),
             rgb(0, 255, 0, max = 255),
             rgb(247,255,0, max = 255),
             rgb(255, 0, 0, max = 255),
             rgb(152,0,0, max=255)
           )),
           showscale = T,
           autocontour = TRUE,
   contours = list(
    coloring = 'heatmap'
  ))


figcon

htmlwidgets::saveWidget(as_widget(figcon), "fig_controlbay_3D_BP_plotly.html")


```

```{r bacterial production - statistical modeling}
#Data exploration
BP.incub <- BP %>% 
  filter(!Time_1 %in% "Start") 
#Outlier 
ggplot(BP.incub, aes(x = ugC.L.d, y = real_temp, color=as.factor(real_temp))) + #outlier at 16 °C
  geom_point()+
  facet_grid(~bay+Time_1)

#Boxplot to test for homogenity
BP.incub %>%
  ggplot( aes(x=real_temp, y=ugC.L.d))+
  geom_boxplot( aes(group=real_temp))+
  facet_grid(~Time_1+bay)

##Normal distribution?
lm_1 <- lm(ugC.L.d ~bay + real_temp + temp_sq + Time_1 + Bio.Replicate, data=BP.incub)
plot(lm_1)
E <- resid(lm_1)
hist(E)


##Graphical investigation
m1 <- lm(ugC.L.d~.^3,data=BP.incub)

m2 <- lm(ugC.L.d~(bay+real_temp+temp_sq+Bio.Replicate+Time_1)^3,data=BP.incub)

#Plot the possible interactions
dwplot(m2)+geom_vline(xintercept=0,lty=2)
#Anova on the possible interactions
anova(m2)


#Model used
B9 <-lm(ugC.L.d ~ bay + bay/Bio.Replicate+ Time_1+ real_temp + temp_sq + Time_1*real_temp + bay*Time_1+ bay*real_temp+ bay*temp_sq + bay*Time_1*real_temp + bay*Time_1*temp_sq, data=BP.incub)

#PLot model
plot(B9)
#normal distribution analysis of the used model
E <- resid(B9)
hist(E)

#Summary of the model
summary(B9)
#ANOVA of the model
anova(B9)


# Separate analysis based for each bay

##heated bay
BP.incub.heat <- BP.incub %>% 
  filter(bay %in% "heated")

B12 <-lm(ugC.L.d ~  Bio.Replicate+ Time_1+ real_temp + temp_sq + Time_1*real_temp , data=BP.incub.heat)

summary(B12)
anova(B12)

# pairwise comparison of the time points
e12 <-emmeans(B12, spec="Time_1",by="real_temp", contr="pairwise")
summary(e12)
frame12


##Control bay
BP.incub.con <- BP.incub %>% filter(bay %in% "control ")

B12 <-lm(ugC.L.d ~  Bio.Replicate+ Time_1+ real_temp + temp_sq + Time_1*real_temp, data=BP.incub.con)
summary(B12)
anova(B12)


# pairwise comparison
e12 <-emmeans(B12, spec="Time_1",by="real_temp", contr="pairwise")
summary(e12)
frame12



#Comparison after 3,6 and 9 days
BP.incub.six <- BP.incub %>% 
  filter(Time_1 %in% "T9") #select the days you want the bays to be compared


B14 <-lm(ugC.L.d ~  bay + bay/Bio.Replicate+ real_temp + temp_sq + bay*real_temp+ bay*temp_sq  , data=BP.incub.six)
summary(B14)
anova(B14)
```

```{r Environmental variables - Figure 1, Figure S4 & S5}
##Make plots for every environmental variables measured for Field and incubation data as wenn as for BW and SED

#Salinity 
BWsal <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
  group_by(bay, temperature_observed)%>%
  mutate(mean=mean(salinity))%>%
  mutate(sd=sd(salinity))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - salininty", x="°C",y="‰")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(6,7)+
  xlim(5,36)

BWsal2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
  filter(!sample %in% c("X1100","X1101","X1102"))%>%
  group_by(bay)%>%
  mutate(mean=mean(salinity))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(salinity))%>%
  ungroup()%>%
  ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - salininty", x="°C",y="‰")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(6.3,6.6)+
  xlim(13,22.5)


#DIC
BWDIC <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
   group_by(bay, temperature_observed)%>%
  mutate(mean=mean(DIC))%>%
  mutate(sd=sd(DIC))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - DIC", x="°C",y="mg/L")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-20,100)

BWDIC2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
  group_by(bay)%>%
  mutate(mean=mean(DIC))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(DIC))%>%
  ungroup()%>%
  ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - DIC", x="°C",y="mg/L")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-20,100)

#DOC
BWDOC <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
   group_by(bay, temperature_observed)%>%
  mutate(mean=mean(DOC))%>%
  mutate(sd=sd(DOC))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - DOC", x="°C",y="mg/L")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,160)

BWDOC2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
  group_by(bay)%>%
  mutate(mean=mean(DOC))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(DOC))%>%
  ungroup()%>%
  ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - DOC", x="°C",y="mg/L")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-40,160)

#Phosphate
BWphos <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
     group_by(bay, temperature_observed)%>%
  mutate(mean=mean(phosphate))%>%
  mutate(sd=sd(phosphate))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - PO4", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-30,100)

BWphos2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
  filter(!sample %in% "X1111")%>%
  group_by(bay)%>%
  mutate(mean=mean(phosphate))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(phosphate))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - PO4", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,400)

#Nitrate+Nitrite in combination
BWnit <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
   group_by(bay, temperature_observed)%>%
  mutate(mean=mean(nitrate))%>%
  mutate(sd=sd(nitrate))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - NO3+NO2", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-2,8)

BWnit2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
    filter(!sample %in% "X1111")%>%
 group_by(bay)%>%
  mutate(mean=mean(nitrate))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(nitrate))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - NO3+NO2", x="bay",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
 ylim(0,14)


#Total Iron
BWiron <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
 group_by(bay, temperature_observed)%>%
  mutate(mean=mean(iron_tot))%>%
  mutate(sd=sd(iron_tot))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - total Iron", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,4.5)

BWiron2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
 group_by(bay)%>%
  mutate(mean=mean(iron_tot))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(iron_tot))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - total Iron", x="bay",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,13)


#Ferrous Iron
BWironII <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
group_by(bay, temperature_observed)%>%
  mutate(mean=mean(iron_II))%>%
  mutate(sd=sd(iron_II))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - ferrous Iron", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,1)

BWironII2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
 group_by(bay)%>%
  mutate(mean=mean(iron_II))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(iron_II))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - ferrous Iron", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,13)

#Sulfate
BWsul <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
 group_by(bay, temperature_observed)%>%
  mutate(mean=mean(sulfate))%>%
  mutate(sd=sd(sulfate))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - sulfate", x="°C",y="mM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,4.5)

BWsul2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
      filter(!sample %in% "X1111")%>%
 group_by(bay)%>%
  mutate(mean=mean(sulfate))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(sulfate))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - sulfate", x="°C",y="mM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,4.0)


#Ammonium
BWammo <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
   filter(!is.na(ammonium))%>%
  group_by(bay, temperature_observed)%>%
  mutate(mean=mean(ammonium))%>%
  mutate(sd=sd(ammonium))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - ammnonium", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  annotate("text", x = 1, y = 6.8, label = "Outlier L ~ 11.3 ‰")+
  theme(legend.position = "bottom")+
  xlim(5,36)+
  ylim(-30,1500)

BWammo2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
  filter(!is.na(ammonium))%>%
  group_by(bay)%>%
  mutate(mean=mean(ammonium))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(ammonium))%>%
  ungroup()%>%
  ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water - ammonium", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  xlim(13,22.5)+
  ylim(-20, 500)

##Sediment
#Nitrate
SEDnit <-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
  group_by(bay, temperature_observed)%>%
  mutate(mean=mean(nitrate))%>%
  mutate(sd=sd(nitrate))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - nitrate", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,100)

SEDnit2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
  group_by(bay)%>%
  mutate(mean=mean(nitrate))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(nitrate))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - nitrate", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,100)


#Nitrite
SEDniti <-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
 group_by(bay, temperature_observed)%>%
  mutate(mean=mean(nitrite))%>%
  mutate(sd=sd(nitrite))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - nitrite", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-1,7.5)

SEDniti2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
   group_by(bay)%>%
  mutate(mean=mean(nitrite))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(nitrite))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - nitrite", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-1,13)

#Total iron
SEDiron1 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
  filter(!sample %in% "X1008")%>%
 group_by(bay, temperature_observed)%>%
  mutate(mean=mean(iron_tot))%>%
  mutate(sd=sd(iron_tot))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - total Iron", x="°C",y="µM")+
  annotate("text", x = 15, y = 2, label = "Outlier B32 ~ 89.6 µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")

SEDiron2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
  group_by(bay)%>%
  mutate(mean=mean(iron_tot))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(iron_tot))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - total Iron", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,30)

#Ferrous Iron
SEDironII <-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
 group_by(bay, temperature_observed)%>%
  mutate(mean=mean(iron_II))%>%
  mutate(sd=sd(iron_II))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - ferrous Iron", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,13)

SEDironII2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
   group_by(bay)%>%
  mutate(mean=mean(iron_II))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(iron_II))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - ferrous Iron", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,13)

#Sulfate
 SEDsul<-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
  group_by(bay, temperature_observed)%>%
  mutate(mean=mean(sulfate))%>%
  mutate(sd=sd(sulfate))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - sulfate", x="°C",y="mM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,4.5)

SEDsul2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
   group_by(bay)%>%
  mutate(mean=mean(sulfate))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(sulfate))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - sulfate", x="°C",y="mM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,4)


#OM
 SEDOM1<-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
 group_by(bay, temperature_observed)%>%
  mutate(mean=mean(OM))%>%
  mutate(sd=sd(OM))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - OM", x="°C",y="%")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,70)

SEDOM2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
  group_by(bay)%>%
  mutate(mean=mean(OM))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(OM))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - OM", x="°C",y="%")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,70)

#DIC
 SEDDIC1<-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
  group_by(bay, temperature_observed)%>%
  mutate(mean=mean(DIC))%>%
  mutate(sd=sd(DIC))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - DIC", x="°C",y="mg/L")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-20,150)

SEDDIC2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
  group_by(bay)%>%
  mutate(mean=mean(DIC))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(DIC))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - DIC", x="°C",y="mg/L")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-20,150)

#DOC
 SEDDOC1<-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
  group_by(bay, temperature_observed)%>%
  mutate(mean=mean(DOC))%>%
  mutate(sd=sd(DOC))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - DIC", x="°C",y="mg/L")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-20,550)

SEDDOC2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
  group_by(bay)%>%
  mutate(mean=mean(DOC))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(DOC))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - DOC", x="°C",y="mg/L")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(-20,550)


#Phosphate
 SEDphos1<-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
  group_by(bay, temperature_observed)%>%
  mutate(mean=mean(phosphate))%>%
  mutate(sd=sd(phosphate))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - phosphate", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,450)

SEDphos2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
  group_by(bay)%>%
  mutate(mean=mean(phosphate))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(phosphate))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - phosphate", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(0,450)


#Ammonium
 SEDamo1<-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
   filter(!is.na(ammonium))%>%
  group_by(bay, temperature_observed)%>%
  mutate(mean=mean(ammonium))%>%
  mutate(sd=sd(ammonium))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - ammonium", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
   ylim(0,1600)

SEDamo2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
     filter(!is.na(ammonium))%>%
  group_by(bay)%>%
  mutate(mean=mean(ammonium))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(ammonium))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment - ammonium", x="°C",y="µM")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")

#pH
Sedph <-  meta%>%
  filter(format %in% "PW")%>%
  filter(!temperature_set %in% "Field")%>%
  group_by(bay, temperature_observed)%>%
  mutate(mean=mean(ph))%>%
  mutate(sd=sd(ph))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment", x="°C",y="pH")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(6.8,9.5)

Sedph2 <-  meta%>%
  filter(format %in% "PW")%>%
  filter(temperature_set %in% "Field")%>%
  group_by(bay)%>%
  mutate(mean=mean(ph))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(ph))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Sediment", x="°C",y="pH")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(6.8,9.5)


#pH
bwph <-  meta%>%
  filter(format %in% "BW")%>%
  filter(!temperature_set %in% "Field")%>%
   group_by(bay, temperature_observed)%>%
  mutate(mean=mean(ph))%>%
  mutate(sd=sd(ph))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water", x="°C",y="pH")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(6.8,9.5)

bwph2 <-  meta%>%
  filter(format %in% "BW")%>%
  filter(temperature_set %in% "Field")%>%
        filter(!sample %in% "X1111")%>%
  group_by(bay)%>%
  mutate(mean=mean(ph))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(ph))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(title="Bottom water", x="°C",y="pH")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  ylim(6.8,9.5)

#BW+SED experiment - Figure 1
ggarrange(bwph,Sedph,BWsal,BWammo, SEDamo1,BWnit,SEDniti,SEDnit,BWironII,SEDironII,BWsul, SEDsul,BWphos, SEDphos1,ncol=5,nrow=3 )


##Supplement other data experiment Figure S5
exp <- ggarrange(BWiron,SEDiron1,SEDOM1,BWDIC,SEDDIC1,BWDOC,SEDDOC1, ncol=3, nrow=3)
field <- ggarrange(BWiron2,SEDiron2,SEDOM2,BWDIC2,SEDDIC2,BWDOC2,SEDDOC2, ncol=3,nrow=3)
ggarrange(field, exp, ncol=2)

##Supplement Field data to compare Figure S4
ggarrange(bwph2,Sedph2,BWsal2,BWammo2, SEDamo2,BWnit2,SEDniti2,SEDnit2,BWironII2,SEDironII2,BWsul2, SEDsul2,BWphos2, SEDphos2,ncol=5,nrow=3 )

```

```{r Environmental variables statistical modeling}
#BW
metaBW <- meta %>% 
          filter(format %in% "BW")%>%
          filter(!temperature_set %in% "Field")

C1 <-lm(DOC ~ bay + bay/samplingsite + temperature_observed + temp_obs_sq + bay*temperature_observed+ bay*temp_obs_sq , data=metaBW)
anova(C1)


emmeans(C1, spec="bay",by="temperature_observed", contr="pairwise")




#SED
metased <- meta %>% 
          filter(format %in% "PW")%>%
          filter(!temperature_set %in% "Field")

C1 <-lm(DOC ~ bay + bay/samplingsite + temperature_observed + temp_obs_sq + bay*temperature_observed+ bay*temp_obs_sq , data=metased)

anova(C1)


emmeans(C1, spec="bay",by="temperature_observed", contr="pairwise")
```

```{r rarefaction}
#Take all samples and make a wide table 
countsRAW_rare <- counts_all %>%  
  dplyr::select(sequence, sample, count) %>%
  spread(sequence,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample")

#Color according to the bays
col <- c ("blue", "orange2")
grp <- factor(meta$bay, levels= c("CONTROL","TEMP_AFFECT"))
cols <- col[grp]

#Chck the smallest sample size and rarefy to the smallest
(raremax <- min(rowSums(countsRAW_rare)))

#Rarefaction curve plot
out <-  rarecurve(countsRAW_rare, step = 20, sample = raremax, col = cols , cex = 0.6)
```

```{r Alpha-Diversity - SAS - Figure 3}
#SED

#SRS analysis
#raw counts from both material BW and SED
example_input_data_SED <- ALL %>%
  filter(format=="PW")%>%
  filter(!sample=="X1006")%>%  
  dplyr::select(sequence, sample, count)%>%
  spread(sample,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sequence")

#(e.g. species counts of the library with the lowest sequencing depth):
Cmin_SED <- min(colSums(example_input_data_SED))
Cmin_SED

SRS_output_SED <- SRS(data = example_input_data_SED, Cmin = Cmin_SED)
SRS_output_SED

##BW

##raw counts from both material BW and SED
example_input_data_BW <- ALL %>%filter(format=="BW")%>%
  dplyr::select(sequence, sample, count)%>%  
  spread(sample,count, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sequence")

#(e.g. species counts of the library with the lowest sequencing depth):
Cmin_BW <- min(colSums(example_input_data_BW))
Cmin_BW

SRS_output_BW <- SRS(data = example_input_data_BW, Cmin = Cmin_BW)
SRS_output_BW



#Shannon Diversity Index
#SED

SRSshannon_SED<- SRS_output_SED %>%
  t()%>%
  data.frame()%>% 
  rownames_to_column(var="sample")%>% 
  plyr::ddply(~sample, function(x) {vegan::diversity(x[-1], index="shannon")}) %>%
  dplyr::rename(shannon= V1) %>% #Shannon 
  left_join(meta, by="sample")

SRSshannon_SED$temperature_set <- factor(SRSshannon_SED$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))

shanSRS_SED_1 <- SRSshannon_SED %>%
  filter(temperature_set %in% "Field")%>%
   group_by(bay)%>%
  mutate(mean=mean(shannon))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(shannon))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(x = "temperature_observed", y = "Shannon Index SED") +
  theme_bw() +
  theme(text = element_text(size = 14)) +
  theme(panel.grid = element_blank(), axis.title.x = element_text(size = 12))+
  ylim(3,8)

shanSRS_SED_2 <- SRSshannon_SED %>%
  filter(!temperature_set %in% c("Field"))%>%
   group_by(bay, temperature_observed)%>%
  mutate(mean=mean(shannon))%>%
  mutate(sd=sd(shannon))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
    labs(x = "temperature_observed", y = "Shannon Index SED") +
  ylim(3,8)


#Plot of Field and incubation experiment Diversity from sediment samples
shannonSED <- ggarrange(shanSRS_SED_1,shanSRS_SED_2, ncol=2 )

#BW
SRSshannon_BW<- SRS_output_BW %>%
  t()%>%
  data.frame()%>% 
  rownames_to_column(var="sample")%>% 
  plyr::ddply(~sample, function(x) {vegan::diversity(x[-1], index="shannon")}) %>%
  dplyr::rename(shannon= V1) %>% #Shannon 
  left_join(meta, by="sample")

SRSshannon_BW$temperature_set <- factor(SRSshannon_BW$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))

shanSRS_BW_1 <- SRSshannon_BW %>%
    filter(temperature_set %in% "Field")%>%
     group_by(bay)%>%
  mutate(mean=mean(shannon))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(shannon))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(x = "temperature_observed", y = "Shannon Index BW") +
  theme_bw() +
  theme(text = element_text(size = 14)) +
  theme(panel.grid = element_blank(), axis.title.x = element_text(size = 12))+
  ylim(1,7)

shanSRS_BW_2 <- SRSshannon_BW %>%
    filter(!temperature_set %in% "Field")%>%
    group_by(bay, temperature_observed)%>%
  mutate(mean=mean(shannon))%>%
  mutate(sd=sd(shannon))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
    labs(x = "temperature_observed", y = "Shannon Index BW") +
  ylim(1,7)

#Plot for Shannon´s H alpha diversity indices from the field and incubation experiment for BW
shannonBW <- ggarrange(shanSRS_BW_1, shanSRS_BW_2, ncol=2)



#Evenness calculations
#SED

B_SED <- SRS_output_SED %>%
        t()%>%
        data.frame()%>% 
        rownames_to_column(var="sample")%>%
        remove_rownames()%>%
        column_to_rownames(var="sample")

H_SED <- SRS_output_SED %>%
      t()%>%
      data.frame()%>% 
      rownames_to_column(var="sample")%>% 
      plyr::ddply(~sample, function(x) {vegan::diversity(x[-1], index="shannon")}) %>%
      dplyr::rename(shannon= V1)

H_SED <- H_SED %>% 
    remove_rownames()%>% 
    column_to_rownames(var="sample")

J_SED <- H_SED/log(specnumber(B_SED))

evenSH_SED <- J_SED %>% 
  rownames_to_column(var="sample")%>%
  left_join(meta, by="sample")


evenSH_SED$temperature_set <- factor(evenSH_SED$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))

ggshaneven_SED_1<- evenSH_SED %>%
      filter(temperature_set %in% "Field")%>%
    group_by(bay)%>%
  mutate(mean=mean(shannon))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(shannon))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(x = "", y = "SED Shannon evenness") +
  theme_bw() +
  theme(text = element_text(size = 14)) +
  theme(panel.grid = element_blank(), axis.title.x = element_text(size = 12))+
  ylim(0.60, 0.99)

ggshaneven_SED_2<- evenSH_SED %>%
      filter(!temperature_set %in% "Field")%>%
      group_by(bay, temperature_observed)%>%
  mutate(mean=mean(shannon))%>%
  mutate(sd=sd(shannon))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  labs(x = "temperature observed", y = "SED Shannon evenness") +
  ylim(0.60, 0.99)


#Plot Shannon´s H evenness calculations for field and incubation experiment for the sediment samples
ggshaneven_SED <- ggarrange(ggshaneven_SED_1,ggshaneven_SED_2)


##BW
B_BW <- SRS_output_BW %>%
        t()%>%
        data.frame()%>% 
        rownames_to_column(var="sample")%>%
        remove_rownames()%>%
        column_to_rownames(var="sample")

H_BW <- SRS_output_BW %>%
      t()%>%
      data.frame()%>% 
      rownames_to_column(var="sample")%>% 
      plyr::ddply(~sample, function(x) {vegan::diversity(x[-1], index="shannon")}) %>%
      dplyr::rename(shannon= V1)

H_BW <- H_BW %>% 
    remove_rownames()%>% 
    column_to_rownames(var="sample")

J_BW <- H_BW/log(specnumber(B_BW))
evenSH_BW <- J_BW %>% 
  rownames_to_column(var="sample")%>%
  left_join(meta, by="sample")

evenSH_BW$temperature_set <- factor(evenSH_BW$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))

ggshaneven_BW_1<- evenSH_BW %>%
     filter(temperature_set %in% "Field")%>%
    group_by(bay)%>%
  mutate(mean=mean(shannon))%>%
  mutate(temp_mean=mean(temperature_observed))%>%
  mutate(sd=sd(shannon))%>%
  ungroup()%>%
 ggplot(aes(x = temp_mean, y = mean, color=bay)) +
  geom_point() +
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9)) +
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  labs(x = "", y = "BW Shannon evenness") +
  theme_bw() +
  theme(text = element_text(size = 14)) +
  theme(panel.grid = element_blank(), axis.title.x = element_text(size = 12))

ggshaneven_BW_2<- evenSH_BW %>%
     filter(!temperature_set %in% "Field")%>%
     group_by(bay, temperature_observed)%>%
  mutate(mean=mean(shannon))%>%
  mutate(sd=sd(shannon))%>%
  ungroup()%>%
  ggplot(aes(x = temperature_observed, y = mean, color=bay)) +
  geom_point() +
  geom_line(aes(group=bay))+
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.3)) +
  geom_smooth(method="lm",aes( group=bay, color=bay))+
scale_color_manual(values=c( "blue","orange"))+
  guides(size=guide_legend(order=2),
         shape= guide_legend(override.aes=list(size=2),
        colour=guide_legend(override.aes=list(size=4))))+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  theme(strip.background = element_rect(colour = "black", fill = "white"))+
  theme_classic()+
  theme(legend.position = "bottom")+
  labs(x = "temperature observed", y = "BW Shannon evenness") 

#Plot for BW Shannon´s H evenness 
ggshaneven_BW <- ggarrange(ggshaneven_BW_1,ggshaneven_BW_2, ncol=2)


#combine Shannon´s and Evenness

ggarrange(shannonBW,ggshaneven_BW,shannonSED,ggshaneven_SED,ncol=2,nrow=2)

```

```{r Alpha-Diversity statistical modeling}
C1 <-lm(shannon ~ bay + bay/samplingsite + temperature_observed + temp_obs_sq + bay*temperature_observed+ bay*temp_obs_sq , data=evenSH_SED)

anova(C1)

emmeans(C1, spec="bay",by="temperature_observed", contr="pairwise")
```

```{r Single and doubletons}
#Wide format with sequence as rows and samples as columns, to sum up each sequence, how often it appears in the samples
Wide_SED <- SED%>% dplyr::select(sequence, sample, count) %>% 
  spread(sample,count, fill= 0)
Wide_BW <- BW%>% dplyr::select(sequence, sample, count) %>% 
  spread(sample,count, fill= 0)

##Remove singletons and doubltons within count data

##SED
data_cleaned_SED = Wide_SED[rowSums(Wide_SED>0)>2,,drop=FALSE]

data_single_double_SED = Wide_SED[!rowSums(Wide_SED>0)>2,,drop=FALSE]

##BW
data_cleaned_BW = Wide_BW[rowSums(Wide_BW>0)>2,,drop=FALSE]

data_single_double_BW = Wide_BW[!rowSums(Wide_BW>0)>2,,drop=FALSE]

```

```{r db-RDA - Figure 4}
#Make data ready for db-RDA analysis

#SED
SED$temperature_set <- factor(SED$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))
SEDsub <- SED
SEDsub <- SEDsub %>% 
  filter(!sample %in%c("X1006"))##Filter as otherwise not possible to combined with env.var

#Wide format
SEDsubwide <- SEDsub %>% 
  dplyr::select(sequence,sample,relab) %>% #select ISV, sample and relab
  spread(sequence,relab, fill= 0) %>% #wide format with sequence and relab, filling gaps with 0
  remove_rownames() %>% #remove of row names
  column_to_rownames(var = "sample")

#Meta table
##SED#
meta$temperature_set <- factor(meta$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))
metasubSED <- meta %>% 
              filter(format =="PW")

metasubSED <- metasubSED %>%  
  dplyr::select(sample,bay, sulfate, iron_II,nitrate, nitrite,phosphate, OM,ammonium,ph, depth,temperature_set, samplingsite, group)

metasubSED <- na.omit(metasubSED)%>%
  filter(!sample %in%c("X1006"))


#BW
BW$temperature_set <- factor(BW$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))
metasubBW<- meta %>% 
  filter(format =="BW")
metasubBW <- metasubBW %>%  
  dplyr::select( sample,  bay,salinity, sulfate,  iron_II,nitrate,phosphate,ammonium,ph, samplingsite, temperature_set,depth,  oxygen_start, group)
metasubBW<- na.omit(metasubBW)

BWsub <- BW %>% filter(!sample %in% "X1111")

BWsubwide <- BWsub %>% dplyr::select(sequence,sample,relab) %>% #select ISV, sample and relab
  spread(sequence,relab, fill= 0) %>% #wide format with sequence and relab, filling gaps with 0
  remove_rownames() %>% #remove of row names
  column_to_rownames(var = "sample")


#db-RDA analysis 

#SED
#Based on relab
#dissimilarity matrix based on Bray Curtis
BC.dist_SED=vegdist(SEDsubwide, distance="bray")

#use capscale to make a db-RDA
dbRDA_SED=capscale(BC.dist_SED~OM + ph + iron_II + sulfate + ammonium +nitrate  + phosphate +depth , data=metasubSED, dist="bray")

#check for collinearity of your env.var.
vifSED<- vif.cca(dbRDA_SED)
vifSED #All can be kept

#Anova with permutation within bays
ctrlb <- how(nperm=999,  blocks=metasubSED$bay)
#set.seed(10)
anova(dbRDA_SED, by = "margin",model="direct", permutations = ctrlb)

##Calculate the eigenvalues for the first and second dimension
dpRDA.eigs    <- dbRDA_SED$CCA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))
dpRDA.eigs.uncon    <- dbRDA_SED$CA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))

#Overview how much will be epxlained by the axis
expl_var <- c(dpRDA.eigs , dpRDA.eigs.uncon) 


#Plot: GGPLOT VERSION#
#Extract site data first
scrs <- scores(dbRDA_SED, display=c("sp","wa","lc","bp","cn"))
df_sites_SED<-data.frame(scrs$sites,t(as.data.frame(strsplit(rownames(scrs$sites),"_"))))
colnames(df_sites_SED)<-c("CAP1","CAP2","sample")

df_sites_SED <- df_sites_SED %>% 
  inner_join(metasubSED, by="sample")

#Draw sites
p_SED<-ggplot()
p_SED<-p_SED+geom_point(data=df_sites_SED,aes(CAP1,CAP2,colour=temperature_set,shape=bay, size=5))+
  scale_color_manual(values=c("grey76", "cadetblue1","deepskyblue3","chartreuse3","bisque","darkorange","coral1","deeppink3","darkred"))

#Draw biplots
multiplier_SED <- vegan:::ordiArrowMul(scrs$biplot*0.3)

df_arrows_SED<- scrs$biplot*multiplier_SED
colnames(df_arrows_SED)<-c("CAP1","CAP2")
df_arrows=as.data.frame(df_arrows_SED)

p_SED<-p_SED+geom_segment(data=as.data.frame(df_arrows_SED), aes(x = 0, y = 0, xend = CAP1, yend = CAP2),
                 arrow = arrow(length = unit(0.2, "cm")))

p_SED<-p_SED+geom_text(data=as.data.frame(df_arrows_SED*1.0),aes(CAP1, CAP2, label = rownames(df_arrows_SED)))+
  theme_classic()+
  theme(legend.position = "bottom")
p_SED



#BW
BC.dist=vegdist(BWsubwide, distance="bray")

dbRDA=capscale(BC.dist~ oxygen_start + ph +  sulfate + iron_II+ammonium  +nitrate + salinity + phosphate +depth, data=metasubBW, dist="bray")

dbRDA

vifBW<- vif.cca(dbRDA)
vifBW##All can be kept


ctrlb <- how(nperm=999,  blocks=metasubBW$bay)
anova(dbRDA, by = "margin",model="direct", permutations = ctrlb)


dpRDA.eigs    <- dbRDA$CCA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))
dpRDA.eigs.uncon    <- dbRDA$CA$eig %>% 
  data.frame() %>% 
  tibble::rownames_to_column('dbRDA') %>%
  rename(eigval = 2) %>%
  mutate(propexpl = eigval/sum(eigval))

expl_var <- c(dpRDA.eigs , dpRDA.eigs.uncon)

#GGPLOT VERSION#
#Extract site data first
scrs <- scores(dbRDA, display=c("sp","wa","lc","bp","cn"))
df_sites<-data.frame(scrs$sites,t(as.data.frame(strsplit(rownames(scrs$sites),"_"))))
colnames(df_sites)<-c("CAP1","CAP2","sample")

df_sites <- df_sites %>% 
  inner_join(metasubBW, by="sample")

#Draw sites
p2<-ggplot()
p2<-p2+geom_point(data=df_sites,aes(CAP1,CAP2,colour=temperature_set,shape=bay, size=5))+
  scale_color_manual(values=c("grey76", "cadetblue1","deepskyblue3","chartreuse3","bisque","darkorange","coral1","deeppink3","darkred"))

#Draw biplots
multiplier <- vegan:::ordiArrowMul(scrs$biplot*0.3)

df_arrows<- scrs$biplot*multiplier
colnames(df_arrows)<-c("CAP1","CAP2")
df_arrows=as.data.frame(df_arrows)

p2<-p2+geom_segment(data=df_arrows, aes(x = 0, y = 0, xend = CAP1, yend = CAP2),
                 arrow = arrow(length = unit(0.2, "cm")))

p2<-p2+geom_text(data=as.data.frame(df_arrows*1.0),aes(CAP1, CAP2, label = rownames(df_arrows)))+
  theme_classic()+
  theme(legend.position = "bottom")
p2

#Combine both plots
ggarrange(p2,p_SED, ncol=2)
```

```{r nMDS - Figure S7}
#SED
asvs_subsed <-  SED%>% 
  dplyr::select(sequence,sample,relab) %>% 
  spread(sequence,relab, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample")

#NMDS
#calculate bray curtis distances with metaMDS function, double check autotransform and trace in metaMDS help!!!
nmds.asvs.h.bc <- metaMDS(asvs_subsed ,
                             distance = "bray",
                             k = 3,
                             trymax = 50,
                             autotransform = FALSE, #set to false when using normalized data from relab
                             trace = FALSE)


nmds.seed.asvs.bc.df <- as.data.frame(nmds.asvs.h.bc$points) %>%
      rownames_to_column(var ="sample") %>%
       dplyr::rename(NMDS1 = MDS1, NMDS2 = MDS2)
 
#check the stress plot should be a nearly linear fit
nmds.asvs.h.bc.stress <- stressplot(nmds.asvs.h.bc)

#Plot nmds for sediment
SED$temperature_set <- factor(SED$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))

p <- nmds.seed.asvs.bc.df %>% inner_join (SED, by="sample")%>%
  ungroup()%>%
  ggplot( aes(x=NMDS1, y=NMDS2, color=temperature_set, shape=bay, label=samplingsite)) +
  geom_point(size = 8) +
  scale_color_manual(values=c("grey76", "cadetblue1","deepskyblue3","chartreuse3","bisque","darkorange","coral1","deeppink3","darkred"))+
  theme_bw() +
  theme(legend.position = "bottom")+
  labs(title = "SED")

p


#BW
asvs_subBW <-  BW%>% 
  dplyr::select(sequence,sample,relab) %>% 
  spread(sequence,relab, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample")

#NMDS
nmds.asvs.h.bcBW <- metaMDS(asvs_subBW ,
                             distance = "bray",
                             k = 3,
                             trymax = 50,
                             autotransform = FALSE, 
                             trace = FALSE) 


nmds.seed.asvs.bc.dfBW <- as.data.frame(nmds.asvs.h.bcBW$points) %>%
      rownames_to_column(var ="sample") %>%
       dplyr::rename(NMDS1 = MDS1, NMDS2 = MDS2)
#Stressplot
nmds.asvs.h.bc.stressBW <- stressplot(nmds.asvs.h.bcBW)

#Plot
BW$temperature_set <- factor(BW$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))

pBW <- nmds.seed.asvs.bc.dfBW %>% 
  inner_join (BW, by="sample")%>%
  ungroup()%>%
  ggplot( aes(x=NMDS1, y=NMDS2, color=temperature_set, shape=bay, label=samplingsite)) +
  geom_point(size = 8) +
  scale_color_manual(values=c("grey76", "cadetblue1","deepskyblue3","chartreuse3","bisque","darkorange","coral1","deeppink3","darkred"))+
  theme_bw() +
  theme(legend.position = "bottom")+
  labs(title = "BW")

pBW

#Combine both nMDS
ggarrange( pBW,p, ncol=2)
```

```{r Phylum overview -Figure S8}
#SED
SED$shortcut <- factor(SED$shortcut,levels=c("K1_Field","K2_Field","K3_Field","L1_Field","L2_Field","L3_Field","M1_Field","M2_Field","M3_Field","K4","L4","M4","K8","L8","M8","K12","L12","M12","K16","L16","M16","K20","L20","M20","K24","L24","M24","K28","L28","M28","K32","L32","M32","B1_Fiedl","B2_Field","B3_Field","D1_Field","D2_Field","D3_Field","F1_Field","F2_Field","F3_Field","B4","D4","F4","B8","D8","F8","B12","D12","F12","B16","D16","F16","B20","D20","F20","B24","D24","F24","B28","D28","F28","B32","D32","F32"))

SED$temperature_set <- factor(SED$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))

SED_field<- SED%>%
  mutate_if(is.character, list(~na_if(.,"")))%>% 
  replace_na(list(Kingdom="Unclassified"))%>% 
  filter(!Kingdom %in% "Unclassified")%>% 
  group_by(Phylum,shortcut,bay,temperature_set,sample)%>%
  summarise(sum = sum(relab))%>%
  summarise(sum=mean(sum))%>%
  ungroup()%>%
  filter(sum >= 0.01)%>% 
  filter(temperature_set %in% "Field")%>%
ggplot(aes(x = shortcut, y = sum, fill = Phylum)) +
geom_bar(position="fill",  stat="identity") +
scale_fill_manual(values=c("#ffbbcc","#c4001e","#ff9a62","#6d3a00","#ff9b05","#fff8eb","#a48600","#487a00","#006744","#00f3d1","#006278","#008cc7","#005bb6","#a9b7ff","#7770ff",
"#450097","#e5b4ff","#a533e6","#160016","#7a005b","#df0099","#ff7dbf"))+
theme(
    legend.position = 'bottom'
)+
  xlab('bay') + ylab('relative abundance ') +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1)
)+
  facet_grid(~bay)

ggarrange(SED_field,SED_exp, ncol=2)

#BW
  BW$shortcut <- factor(BW$shortcut,levels=c("K1_Field","K2_Field","K3_Field","L1_Field","L2_Field","L3_Field","M1_Field","M2_Field","M3_Field","K4","L4","M4","K8","L8","M8","K12","L12","M12","K16","L16","M16","K20","L20","M20","K24","L24","M24","K28","L28","M28","K32","L32","M32","B1_Fiedl","B2_Field","B3_Field","D1_Field","D2_Field","D3_Field","F1_Field","F2_Field","F3_Field","B4","D4","F4","B8","D8","F8","B12","D12","F12","B16","D16","F16","B20","D20","F20","B24","D24","F24","B28","D28","F28","B32","D32","F32"))

BW_field<- BW%>%
  mutate_if(is.character, list(~na_if(.,"")))%>% 
  replace_na(list(Kingdom="Unclassified"))%>% 
  filter(!Kingdom %in% "Unclassified")%>% 
  group_by(Phylum,shortcut,bay,temperature_set,sample)%>%
  summarise(sum = sum(relab))%>%
  summarise(sum=mean(sum))%>%
  ungroup()%>%
  filter(sum >= 0.01)%>% 
  filter(temperature_set %in% "Field")%>%
ggplot(aes(x = shortcut, y = sum, fill = Phylum)) +
geom_bar(position="fill",  stat="identity") +
scale_fill_manual(values=c(
                          "#a40027","#ff585a","#ff8e44","#503e00","#7d8a00","#4edb13",
                          #  "#acff90",
                          # "#006a04",
                          # "#5fffcc",
                          # "#018afd",
                          # "#014bea",
                           "#210055",
                          "#b53aed",
                          "#ff98ff",
                         "pink",
                         # "#ff2dc6",
                          "#ffdbee",
                          "#ae006a",
                          "grey76"))+
theme(
    legend.position = 'bottom'
)+
  xlab('bay') + ylab('relative abundance ') +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1)
)+
  facet_grid(~bay)

#Combine both plots
ggarrange(BW_field,BW_exp, ncol=2)
```

```{r Temperature response - Differential abundance analysis - Bottom water}
#Differential abundance analysis was done within the experiment samples, to minimize the effect of the experiment on the results, therefore samples were compared to the samples where the temperature fits the field temperature.
##Make an phyloseq object
OTU <- BW%>%
  filter(bay %in% "CONTROL")%>%#Testing each bay by itself
    filter(group %in% "experiment")%>%
  group_by(sequence, sample)%>%
  summarise(count=sum(count))%>%
  dplyr::select(sequence, sample, count)%>% 
  spread(sample, count,fill=0 ) %>%
  column_to_rownames("sequence")

TAXA <- taxa %>% 
  semi_join(BW, by=c("sequence","Kingdom","Family","Order","Class","Genus","Species"))%>% 
  remove_rownames()%>%
  column_to_rownames(var="sequence")

SAMPLES <- meta %>%
    filter(bay %in% "CONTROL")%>%
    filter(group %in% "experiment")%>%
          filter(format %in% "BW")%>%
          remove_rownames() %>% 
          column_to_rownames(var="sample")

OTU <- as.matrix(OTU)
TAXA <- as.matrix(TAXA)

  OTU = otu_table(OTU, taxa_are_rows = TRUE)
  TAX = tax_table(TAXA)
  samples = sample_data(SAMPLES)
  
  carbom <- phyloseq(OTU, TAX, samples)
  carbom

##Get rid of low abundant Taxa
species_counts_df <- data.frame(otu_table(carbom))
(sum(colSums(species_counts_df == 0))) / (nrow(species_counts_df) * ncol(species_counts_df))


##Assessing zero proportion after filtering
species_counts_df <- data.frame(otu_table(carbom))
species_counts_df <- data.frame(t(species_counts_df))


dds_zinbwave <- phyloseq_to_deseq2(carbom, ~ temperature_observed)
ds_zinbwave <- zinbwave(dds_zinbwave,
                   X="~ 1",
                   epsilon = 1e10,
                   verbose = TRUE,
                   K = 0,
                   observationalWeights = TRUE,
                   BPPARAM = BiocParallel::SerialParam())


dds_zinb <- DESeqDataSet(dds_zinbwave, design = ~ temperature_observed)
   dds_zinb$groups <- factor(paste0( dds_zinb$temperature_observed))
   design(dds_zinb)<- ~groups
dds_zinb <- estimateSizeFactors(dds_zinb, type="poscounts")
scr <- computeSumFactors(dds_zinb) 

sizeFactors(dds_zinb) <- sizeFactors(scr)

###Fit the model use the LRT 
dds_zinb <- DESeq(dds_zinb, test="LRT", reduced=~1, sfType="poscounts",
                  minmu=1e-6, minReplicatesForReplace=Inf, fitType = "local")

plotMA(dds_zinb)
plotDispEsts(dds_zinb)  

###Make contrast so you can differentiate between the groups you are looking for
   resultsNames(dds_zinb)
   TDE6 <- results(dds_zinb, contrast=c("groups","15","6")) 
   TDE8 <-results(dds_zinb, contrast=c("groups","15","8")) 
   TDE24 <-results(dds_zinb, contrast=c("groups","15","24"))
   TDE16 <-results(dds_zinb, contrast=c("groups","15","16"))
   TDE25 <-results(dds_zinb, contrast=c("groups","15","25"))
   TDE28 <-results(dds_zinb, contrast=c("groups","15","28"))
   TDE35 <-results(dds_zinb, contrast=c("groups","15","35"))

##make it readable  
    DE2_results <- data.frame(TDE35)
    baseMeanPerLvl <- sapply( levels(dds_zinb$groups), function(lvl) rowMeans(counts(dds_zinb,normalized=TRUE)[,dds_zinb$groups == lvl] ) )
    DE2_results <-merge(DE2_results,baseMeanPerLvl, by="row.names")
  DE2_results<- DE2_results[,c(1,2,13,8,3,4,5,6,7)]

    sorted_DE2_results <- DE2_results[order(-DE2_results$baseMean),]
    colnames(sorted_DE2_results)[1] <- "sequence"
   
    sorted_taxa <- sorted_DE2_results %>% left_join(taxa, by="sequence")
    
   
    write.csv(sorted_taxa , "Deseq_differential_abundance_control_BW_15_vs_35_INCUB_ASV_level_interaction.csv")
    
    
    
##heated bay

##24 vs 6
Basevs6 <- read.csv("Deseq_differential_abundance_heated_BW_24_vs_6_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

Fieldfilt <- Basevs6 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-"X24",-"X6")

Fieldvs6_BW <-  BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "TEMP_AFFECT")%>%
  filter(temperature_observed %in% c("24","6"))


Fieldfull <- Fieldfilt %>% 
            left_join(Fieldvs6_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 8

FV8 <- read.csv("Deseq_differential_abundance_heated_BW_24_vs_8_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV8filt <- FV8 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-X24,-X8)

FV8_BW <-  BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "TEMP_AFFECT")%>%
  filter(temperature_observed %in% c("24","8"))


FV8full <- FV8filt %>% 
            left_join(FV8_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))

##Field vs 15
FV15 <- read.csv("Deseq_differential_abundance_heated_BW_24_vs_15_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV15filt <- FV15 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-X24,-X15)

FV15_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "TEMP_AFFECT")%>%
  filter(temperature_observed %in% c("24","15"))


FV15full <- FV15filt %>% 
            left_join(FV15_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 16
FV16 <- read.csv("Deseq_differential_abundance_heated_BW_24_vs_16_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV16filt <- FV16 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
                      dplyr::select(-X24,-X16)

FV16_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "TEMP_AFFECT")%>%
  filter(temperature_observed %in% c("24","16"))


FV16full <- FV16filt %>% 
            left_join(FV16_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))



##Field vs 25
FV25 <- read.csv("Deseq_differential_abundance_heated_BW_24_vs_25_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV25filt <- FV25 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-X24,-X25)

FV25_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "TEMP_AFFECT")%>%
  filter(temperature_observed %in% c("24","25"))



FV25full <- FV25filt %>% 
            left_join(FV25_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 28
FV28 <- read.csv("Deseq_differential_abundance_heated_BW_24_vs_28_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV28filt <- FV28 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-X24,-X28)

FV28_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "TEMP_AFFECT")%>%
  filter(temperature_observed %in% c("24","28"))



FV28full <- FV28filt %>% 
            left_join(FV28_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))

##Field vs 35
FV35 <- read.csv("Deseq_differential_abundance_heated_BW_24_vs_35_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV35filt <- FV35 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-X24,-X35)

FV35_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "TEMP_AFFECT")%>%
  filter(temperature_observed %in% c("24","35"))


FV35full <- FV35filt %>% 
            left_join(FV35_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Combine tables

heatedBW_DA <- rbind(Fieldfull,FV8full,FV15full,FV16full,FV25full,FV28full,FV35full)%>%
  filter(!temperature_observed %in% "24")


##control bay

##Field vs 6
Basevs6 <- read.csv("Deseq_differential_abundance_control_BW_15_vs_6_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

Fieldfilt <- Basevs6 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-"X15",-"X6")

Fieldvs6_BW <-  BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "CONTROL")%>%
  filter(temperature_observed %in% c("15","6"))


Fieldfull <- Fieldfilt %>% 
            left_join(Fieldvs6_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 8

FV8 <- read.csv("Deseq_differential_abundance_control_BW_15_vs_8_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV8filt <- FV8 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-X15,-X8)

FV8_BW <-  BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "CONTROL")%>%
  filter(temperature_observed %in% c("15","8"))


FV8full <- FV8filt %>% 
            left_join(FV8_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))

##Field vs 24
FV24 <- read.csv("Deseq_differential_abundance_control_BW_15_vs_24_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV24filt <- FV24 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-X15,-X24)

FV24_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "CONTROL")%>%
  filter(temperature_observed %in% c("24","15"))


FV24full <- FV24filt %>% 
            left_join(FV24_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 16
FV16 <- read.csv("Deseq_differential_abundance_control_BW_15_vs_16_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV16filt <- FV16 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
                      dplyr::select(-X15,-X16)

FV16_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "CONTROL")%>%
  filter(temperature_observed %in% c("15","16"))


FV16full <- FV16filt %>% 
            left_join(FV16_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))



##Field vs 25
FV25 <- read.csv("Deseq_differential_abundance_control_BW_15_vs_25_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV25filt <- FV25 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-X15,-X25)

FV25_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "CONTROL")%>%
  filter(temperature_observed %in% c("15","25"))



FV25full <- FV25filt %>% 
            left_join(FV25_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 28
FV28 <- read.csv("Deseq_differential_abundance_control_BW_15_vs_28_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV28filt <- FV28 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-X15,-X28)

FV28_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "CONTROL")%>%
  filter(temperature_observed %in% c("15","28"))



FV28full <- FV28filt %>% 
            left_join(FV28_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))

##Field vs 35
FV35 <- read.csv("Deseq_differential_abundance_control_BW_15_vs_35_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV35filt <- FV35 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-X15,-X35)

FV35_BW <- BW%>%
  filter(!group %in% "Field")%>%
  filter(bay %in% "CONTROL")%>%
  filter(temperature_observed %in% c("15","35"))


FV35full <- FV35filt %>% 
            left_join(FV35_BW, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Combine tables

controlBW_DA <- rbind(Fieldfull,FV8full,FV24full,FV16full,FV25full,FV28full,FV35full)%>%
  filter(!temperature_observed %in% "15")


controlBW_DA_sub <-  controlBW_DA  %>%
  filter(!temperature_observed %in% "15")%>%
  filter(group %in% "experiment")%>%
 filter(!is.na(sample))

heatedBW_DA_sub <-  heatedBW_DA %>%
  filter(!temperature_observed %in% "24")%>%
  filter(group %in% "experiment")%>%
 filter(!is.na(sample))

BW_DA <- rbind(heatedBW_DA_sub, controlBW_DA_sub)

asvs_subBW <-  BW_DA %>%
  dplyr::select(sequence,sample,relab) %>% 
  spread(sequence,relab, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample")
```

```{r Temperature response - Differential abundance analysis - Sediment}
#Differential abundance analysis, to compare Field with incubation samples, to investigate on potential differential abundant ASVS in response to temperature

#Make an phyloseq object
OTU <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "M")%>%#Analysis was done by samplingsite, as they are very diverse
  group_by(sequence, sample)%>%
  summarise(count=sum(count))%>%
  dplyr::select(sequence, sample, count)%>% 
  spread(sample, count,fill=0 ) %>%
  column_to_rownames("sequence")

TAXA <- taxa %>% 
  semi_join(SED, by=c("sequence","Kingdom","Family","Order","Class","Genus","Species"))%>% 
  remove_rownames()%>%
  column_to_rownames(var="sequence")

SAMPLES <- meta %>%
  filter(samplingsite %in% "M")%>%
          filter(format %in% "PW")%>%
          filter(!sample %in% ("X1006"))%>%
          remove_rownames() %>% 
          column_to_rownames(var="sample")

OTU <- as.matrix(OTU)
TAXA <- as.matrix(TAXA)

  OTU = otu_table(OTU, taxa_are_rows = TRUE)
  TAX = tax_table(TAXA)
  samples = sample_data(SAMPLES)
  
#Phyloseq object  
  carbom <- phyloseq(OTU, TAX, samples)
  carbom

#Get rid of low abundant Taxa
species_counts_df <- data.frame(otu_table(carbom))
(sum(colSums(species_counts_df == 0))) / (nrow(species_counts_df) * ncol(species_counts_df))


#Assessing zero proportion after filtering
species_counts_df <- data.frame(otu_table(carbom))
species_counts_df <- data.frame(t(species_counts_df))


dds_zinbwave <- phyloseq_to_deseq2(carbom, ~ group+temperature_observed)
ds_zinbwave <- zinbwave(dds_zinbwave,
                   X="~ 1",
                   epsilon = 1e10,
                   verbose = TRUE,
                   K = 0,
                   observationalWeights = TRUE,
                   BPPARAM = BiocParallel::SerialParam())


dds_zinb <- DESeqDataSet(dds_zinbwave, design = ~ group+temperature_observed) #Our model includes the different temperatures, as well as Field and incubation study
   dds_zinb$groups <- factor(paste0(dds_zinb$group, dds_zinb$temperature_observed))
   design(dds_zinb)<- ~groups
dds_zinb <- estimateSizeFactors(dds_zinb, type="poscounts")
scr <- computeSumFactors(dds_zinb) 

sizeFactors(dds_zinb) <- sizeFactors(scr)

#Fit the model use the LRT 
dds_zinb <- DESeq(dds_zinb, test="LRT", reduced=~1, sfType="poscounts",
                  minmu=1e-6, minReplicatesForReplace=Inf, fitType = "local")

plotMA(dds_zinb)
plotDispEsts(dds_zinb)  

#Make contrast so you can differentiate between the groups you are looking for
   resultsNames(dds_zinb)
   TDE6 <- results(dds_zinb, contrast=c("groups","field12.2","experiment6")) 
   TDE8 <-results(dds_zinb, contrast=c("groups","field12.2","experiment8")) 
   TDE15 <-results(dds_zinb, contrast=c("groups","field12.2","experiment15"))
   TDE16 <-results(dds_zinb, contrast=c("groups","field12.2","experiment16"))
   TDE24 <-results(dds_zinb, contrast=c("groups","field12.2","experiment24"))
   TDE25 <-results(dds_zinb, contrast=c("groups","field12.2","experiment25"))
   TDE28 <-results(dds_zinb, contrast=c("groups","field12.2","experiment28"))
 TDE35 <-results(dds_zinb, contrast=c("groups","field12.2","experiment35"))
#make it readable  
    DE2_results <- data.frame(TDE25)
    baseMeanPerLvl <- sapply( levels(dds_zinb$group), function(lvl) rowMeans(counts(dds_zinb,normalized=TRUE)[,dds_zinb$group == lvl] ) )
    DE2_results <-merge(DE2_results,baseMeanPerLvl, by="row.names")

    sorted_DE2_results <- DE2_results[order(-DE2_results$baseMean),]
    colnames(sorted_DE2_results)[1] <- "sequence"
   
    sorted_taxa <- sorted_DE2_results %>% left_join(taxa, by="sequence")
    
   
    write.csv(sorted_taxa , "Deseq_differential_abundance_SITE_M_Field_vs_25_INCUB_ASV_level_interaction.csv")
    
#Combine the results of each sampling site into one tables 

##SITE D

##Field vs 6
Fieldvs6 <- read.csv("Deseq_differential_abundance_SITE_D_Field_vs_6_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

Fieldfilt <- Fieldvs6 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

Fieldvs6_SED <-  SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "D")%>%
  filter(temperature_set %in% c("Field","4"))


Fieldfull <- Fieldfilt %>% 
            left_join(Fieldvs6_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 8

FV8 <- read.csv("Deseq_differential_abundance_SITE_D_Field_vs_8_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV8filt <- FV8 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV8_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "D")%>%
  filter(temperature_set %in% c("Field","8"))


FV8full <- FV8filt %>% 
            left_join(FV8_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))

##Field vs 15
FV15 <- read.csv("Deseq_differential_abundance_SITE_D_Field_vs_15_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV15filt <- FV15 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV15_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "D")%>%
  filter(temperature_set %in% c("Field","12"))


FV15full <- FV15filt %>% 
            left_join(FV15_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 16
FV16 <- read.csv("Deseq_differential_abundance_SITE_D_Field_vs_16_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV16filt <- FV16 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
                      dplyr::select(-field,-experiment)

FV16_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "D")%>%
  filter(temperature_set %in% c("Field","16"))


FV16full <- FV16filt %>% 
            left_join(FV16_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 24
FV24 <- read.csv("Deseq_differential_abundance_SITE_D_Field_vs_24_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV24filt <- FV24 %>% filter(padj <0.05) %>% 
      filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV24_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "D")%>%
  filter(temperature_set %in% c("Field","20"))


FV24full <- FV24filt %>% 
            left_join(FV24_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 25
FV25 <- read.csv("Deseq_differential_abundance_SITE_D_Field_vs_25_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV25filt <- FV25 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV25_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "D")%>%
  filter(temperature_set %in% c("Field","24"))


FV25full <- FV25filt %>% 
            left_join(FV25_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 28
FV28 <- read.csv("Deseq_differential_abundance_SITE_D_Field_vs_28_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV28filt <- FV28 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV28_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "D")%>%
  filter(temperature_set %in% c("Field","28"))


FV28full <- FV28filt %>% 
            left_join(FV28_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))

##Field vs 35
FV35 <- read.csv("Deseq_differential_abundance_SITE_D_Field_vs_35_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV35filt <- FV35 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV35_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "D")%>%
  filter(temperature_set %in% c("Field","32"))


FV35full <- FV35filt %>% 
            left_join(FV35_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Combine tables

SiteD_DA <- rbind(Fieldfull,FV8full,FV15full,FV16full,FV24full,FV25full,FV28full,FV35full)

##SITE B

##Field vs 6
Fieldvs6 <- read.csv("Deseq_differential_abundance_SITE_B_Field_vs_6_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

Fieldfilt <- Fieldvs6 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

Fieldvs6_SED <-  SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "B")%>%
  filter(temperature_set %in% c("Field","4"))


Fieldfull <- Fieldfilt %>% 
            left_join(Fieldvs6_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 8

FV8 <- read.csv("Deseq_differential_abundance_SITE_B_Field_vs_8_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV8filt <- FV8 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV8_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "B")%>%
  filter(temperature_set %in% c("Field","8"))


FV8full <- FV8filt %>% 
            left_join(FV8_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))

##Field vs 15
FV15 <- read.csv("Deseq_differential_abundance_SITE_B_Field_vs_15_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV15filt <- FV15 %>% filter(padj <0.05) %>%
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV15_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "B")%>%
  filter(temperature_set %in% c("Field","12"))


FV15full <- FV15filt %>% 
            left_join(FV15_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 16
FV16 <- read.csv("Deseq_differential_abundance_SITE_B_Field_vs_16_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV16filt <- FV16 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
                      dplyr::select(-field,-experiment)

FV16_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "B")%>%
  filter(temperature_set %in% c("Field","16"))


FV16full <- FV16filt %>% 
            left_join(FV16_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 24
FV24 <- read.csv("Deseq_differential_abundance_SITE_B_Field_vs_24_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV24filt <- FV24 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV24_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "B")%>%
  filter(temperature_set %in% c("Field","20"))


FV24full <- FV24filt %>% 
            left_join(FV24_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))



##Field vs 28
FV28 <- read.csv("Deseq_differential_abundance_SITE_B_Field_vs_28_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV28filt <- FV28 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV28_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "B")%>%
  filter(temperature_set %in% c("Field","28"))


FV28full <- FV28filt %>% 
            left_join(FV28_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))

##Field vs 35
FV35 <- read.csv("Deseq_differential_abundance_SITE_B_Field_vs_35_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV35filt <- FV35 %>% filter(padj <0.05) %>%
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV35_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "B")%>%
  filter(temperature_set %in% c("Field","32"))


FV35full <- FV35filt %>% 
            left_join(FV35_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Combine tables

SiteB_DA <- rbind(Fieldfull,FV8full,FV15full,FV16full,FV24full,FV28full,FV35full)


##SITE F

##Field vs 6
Fieldvs6 <- read.csv("Deseq_differential_abundance_SITE_F_Field_vs_6_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

Fieldfilt <- Fieldvs6 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

Fieldvs6_SED <-  SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "F")%>%
  filter(temperature_set %in% c("Field","4"))


Fieldfull <- Fieldfilt %>% 
            left_join(Fieldvs6_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 8

FV8 <- read.csv("Deseq_differential_abundance_SITE_F_Field_vs_8_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV8filt <- FV8 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV8_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "F")%>%
  filter(temperature_set %in% c("Field","8"))


FV8full <- FV8filt %>% 
            left_join(FV8_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))

##Field vs 15
FV15 <- read.csv("Deseq_differential_abundance_SITE_F_Field_vs_15_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV15filt <- FV15 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV15_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "F")%>%
  filter(temperature_set %in% c("Field","12"))


FV15full <- FV15filt %>% 
            left_join(FV15_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 16
FV16 <- read.csv("Deseq_differential_abundance_SITE_F_Field_vs_16_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV16filt <- FV16 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
                      dplyr::select(-field,-experiment)

FV16_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "F")%>%
  filter(temperature_set %in% c("Field","16"))


FV16full <- FV16filt %>% 
            left_join(FV16_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 24
FV24 <- read.csv("Deseq_differential_abundance_SITE_F_Field_vs_24_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV24filt <- FV24 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV24_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "F")%>%
  filter(temperature_set %in% c("Field","20"))


FV24full <- FV24filt %>% 
            left_join(FV24_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 25
FV25 <- read.csv("Deseq_differential_abundance_SITE_F_Field_vs_25_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV25filt <- FV25 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV25_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "F")%>%
  filter(temperature_set %in% c("Field","24"))


FV25full <- FV25filt %>% 
            left_join(FV25_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 28
FV28 <- read.csv("Deseq_differential_abundance_SITE_F_Field_vs_28_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV28filt <- FV28 %>% filter(padj <0.05) %>% 
         filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV28_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "F")%>%
  filter(temperature_set %in% c("Field","28"))


FV28full <- FV28filt %>% 
            left_join(FV28_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))

##Field vs 35
FV35 <- read.csv("Deseq_differential_abundance_SITE_F_Field_vs_35_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV35filt <- FV35 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV35_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "F")%>%
  filter(temperature_set %in% c("Field","32"))


FV35full <- FV35filt %>% 
            left_join(FV35_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Combine tables

SiteF_DA <- rbind(Fieldfull,FV8full,FV15full,FV16full,FV24full,FV25full,FV28full,FV35full)


##SITE K

##Field vs 6
Fieldvs6 <- read.csv("Deseq_differential_abundance_SITE_K_Field_vs_6_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

Fieldfilt <- Fieldvs6 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

Fieldvs6_SED <-  SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "K")%>%
  filter(temperature_set %in% c("Field","4"))


Fieldfull <- Fieldfilt %>% 
            left_join(Fieldvs6_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 8

FV8 <- read.csv("Deseq_differential_abundance_SITE_K_Field_vs_8_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV8filt <- FV8 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV8_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "K")%>%
  filter(temperature_set %in% c("Field","8"))


FV8full <- FV8filt %>% 
            left_join(FV8_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))

##Field vs 15
FV15 <- read.csv("Deseq_differential_abundance_SITE_K_Field_vs_15_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV15filt <- FV15 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV15_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "K")%>%
  filter(temperature_set %in% c("Field","12"))


FV15full <- FV15filt %>% 
            left_join(FV15_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 16
FV16 <- read.csv("Deseq_differential_abundance_SITE_K_Field_vs_16_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV16filt <- FV16 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
                      dplyr::select(-field,-experiment)

FV16_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "K")%>%
  filter(temperature_set %in% c("Field","16"))


FV16full <- FV16filt %>% 
            left_join(FV16_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 24
FV24 <- read.csv("Deseq_differential_abundance_SITE_K_Field_vs_24_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV24filt <- FV24 %>% filter(padj <0.05) %>% 
      filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV24_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "K")%>%
  filter(temperature_set %in% c("Field","20"))


FV24full <- FV24filt %>% 
            left_join(FV24_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 25
FV25 <- read.csv("Deseq_differential_abundance_SITE_K_Field_vs_25_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV25filt <- FV25 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV25_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "K")%>%
  filter(temperature_set %in% c("Field","24"))


FV25full <- FV25filt %>% 
            left_join(FV25_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 28
FV28 <- read.csv("Deseq_differential_abundance_SITE_K_Field_vs_28_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV28filt <- FV28 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV28_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "K")%>%
  filter(temperature_set %in% c("Field","28"))


FV28full <- FV28filt %>% 
            left_join(FV28_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))

##Field vs 35
FV35 <- read.csv("Deseq_differential_abundance_SITE_K_Field_vs_35_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV35filt <- FV35 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV35_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "K")%>%
  filter(temperature_set %in% c("Field","32"))


FV35full <- FV35filt %>% 
            left_join(FV35_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Combine tables

SiteK_DA <- rbind(Fieldfull,FV8full,FV15full,FV16full,FV24full,FV25full,FV28full,FV35full)


##SITE L

##Field vs 6
Fieldvs6 <- read.csv("Deseq_differential_abundance_SITE_L_Field_vs_6_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

Fieldfilt <- Fieldvs6 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

Fieldvs6_SED <-  SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "L")%>%
  filter(temperature_set %in% c("Field","4"))


Fieldfull <- Fieldfilt %>% 
            left_join(Fieldvs6_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 8

FV8 <- read.csv("Deseq_differential_abundance_SITE_L_Field_vs_8_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV8filt <- FV8 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV8_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "L")%>%
  filter(temperature_set %in% c("Field","8"))


FV8full <- FV8filt %>% 
            left_join(FV8_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))

##Field vs 15
FV15 <- read.csv("Deseq_differential_abundance_SITE_L_Field_vs_15_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV15filt <- FV15 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV15_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "L")%>%
  filter(temperature_set %in% c("Field","12"))


FV15full <- FV15filt %>% 
            left_join(FV15_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 16
FV16 <- read.csv("Deseq_differential_abundance_SITE_L_Field_vs_16_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV16filt <- FV16 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
                      dplyr::select(-field,-experiment)

FV16_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "L")%>%
  filter(temperature_set %in% c("Field","16"))


FV16full <- FV16filt %>% 
            left_join(FV16_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 24
FV24 <- read.csv("Deseq_differential_abundance_SITE_L_Field_vs_24_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV24filt <- FV24 %>% filter(padj <0.05) %>% 
      filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV24_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "L")%>%
  filter(temperature_set %in% c("Field","20"))


FV24full <- FV24filt %>% 
            left_join(FV24_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 25
FV25 <- read.csv("Deseq_differential_abundance_SITE_L_Field_vs_25_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV25filt <- FV25 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV25_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "L")%>%
  filter(temperature_set %in% c("Field","24"))


FV25full <- FV25filt %>% 
            left_join(FV25_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 28
FV28 <- read.csv("Deseq_differential_abundance_SITE_L_Field_vs_28_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV28filt <- FV28 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV28_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "L")%>%
  filter(temperature_set %in% c("Field","28"))


FV28full <- FV28filt %>% 
            left_join(FV28_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))

##Field vs 35
FV35 <- read.csv("Deseq_differential_abundance_SITE_L_Field_vs_35_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV35filt <- FV35 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV35_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "L")%>%
  filter(temperature_set %in% c("Field","32"))


FV35full <- FV35filt %>% 
            left_join(FV35_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Combine tables

SiteL_DA <- rbind(Fieldfull,FV8full,FV15full,FV16full,FV24full,FV25full,FV28full,FV35full)


##SITE M

##Field vs 6
Fieldvs6 <- read.csv("Deseq_differential_abundance_SITE_M_Field_vs_6_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

Fieldfilt <- Fieldvs6 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

Fieldvs6_SED <-  SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "M")%>%
  filter(temperature_set %in% c("Field","4"))


Fieldfull <- Fieldfilt %>% 
            left_join(Fieldvs6_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 8

FV8 <- read.csv("Deseq_differential_abundance_SITE_M_Field_vs_8_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV8filt <- FV8 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV8_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "M")%>%
  filter(temperature_set %in% c("Field","8"))


FV8full <- FV8filt %>% 
            left_join(FV8_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))

##Field vs 15
FV15 <- read.csv("Deseq_differential_abundance_SITE_M_Field_vs_15_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV15filt <- FV15 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
               dplyr::select(-field,-experiment)

FV15_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
  filter(samplingsite %in% "M")%>%
  filter(temperature_set %in% c("Field","12"))


FV15full <- FV15filt %>% 
            left_join(FV15_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))%>%
                 filter(!is.na(sample))


##Field vs 16
FV16 <- read.csv("Deseq_differential_abundance_SITE_M_Field_vs_16_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV16filt <- FV16 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
                      dplyr::select(-field,-experiment)

FV16_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "M")%>%
  filter(temperature_set %in% c("Field","16"))


FV16full <- FV16filt %>% 
            left_join(FV16_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 24
FV24 <- read.csv("Deseq_differential_abundance_SITE_M_Field_vs_24_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV24filt <- FV24 %>% filter(padj <0.05) %>% 
      filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV24_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "M")%>%
  filter(temperature_set %in% c("Field","20"))


FV24full <- FV24filt %>% 
            left_join(FV24_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 25
FV25 <- read.csv("Deseq_differential_abundance_SITE_M_Field_vs_25_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV25filt <- FV25 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV25_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "M")%>%
  filter(temperature_set %in% c("Field","24"))


FV25full <- FV25filt %>% 
            left_join(FV25_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Field vs 28
FV28 <- read.csv("Deseq_differential_abundance_SITE_M_Field_vs_28_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV28filt <- FV28 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV28_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "M")%>%
  filter(temperature_set %in% c("Field","28"))


FV28full <- FV28filt %>% 
            left_join(FV28_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))

##Field vs 35
FV35 <- read.csv("Deseq_differential_abundance_SITE_M_Field_vs_35_INCUB_ASV_level_interaction.csv", stringsAsFactors = FALSE)%>% 
  anti_join(phyto, by="sequence")

FV35filt <- FV35 %>% filter(padj <0.05) %>% 
     filter(!between(log2FoldChange, -5, 5))%>%
             dplyr::select(-field,-experiment)

FV35_SED <- SED%>%
  filter(!sample %in% "X1006")%>%
 filter(samplingsite %in% "M")%>%
  filter(temperature_set %in% c("Field","32"))


FV35full <- FV35filt %>% 
            left_join(FV35_SED, by=c("sequence","Kingdom","Phylum","Class","Family","Order","Genus","Species"))


##Combine tables

SiteM_DA <- rbind(Fieldfull,FV8full,FV15full,FV16full,FV24full,FV25full,FV28full,FV35full)


###SED
distsedD <- SiteD_DA %>%
  filter(group %in% "experiment")


distsedB <- SiteB_DA %>%
    filter(group %in% "experiment")


distsedF <- SiteF_DA %>%
    filter(group %in% "experiment")


distsedK <- SiteK_DA %>%
    filter(group %in% "experiment")


distsedL <- SiteL_DA %>%
    filter(group %in% "experiment")


distsedM <- SiteM_DA %>%
    filter(group %in% "experiment")


distsed <- rbind(distsedB, distsedD, distsedF, distsedK,distsedL, distsedM)

# wide format prepration for nMDS analysis
asvs_subsed <-  distsed%>%
  dplyr::select(sequence,sample,relab) %>% 
  spread(sequence,relab, fill= 0) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "sample")

```

```{r Temperatre response nMDS - Figure 5}
#BW
#NMDS
nmds.asvs.h.bc <- metaMDS(asvs_subBW,
                             distance = "bray",
                             k = 3,
                             trymax = 50,
                             autotransform = FALSE, # set to false when using normalized data from relab
                             trace = FALSE) 


nmds.seed.asvs.bc.df <- as.data.frame(nmds.asvs.h.bc$points) %>%
      rownames_to_column(var ="sample") %>%
       dplyr::rename(NMDS1 = MDS1, NMDS2 = MDS2)
 
     # check the stress plot should be a nearly linear fit
nmds.asvs.h.bc.stress <- stressplot(nmds.asvs.h.bc)



p <- nmds.seed.asvs.bc.df %>% inner_join (BW, by="sample")%>%
  ungroup()%>%
  ggplot( aes(x=NMDS1, y=NMDS2, color=as.factor(temperature_observed), shape=bay, label=samplingsite)) +
  geom_point(size = 8) +
  scale_color_manual(values=c( "cadetblue1","deepskyblue3","chartreuse3","bisque","darkorange","coral1","deeppink3","darkred"))+
  theme_bw() +
  theme(legend.position = "bottom")+
  labs(title = "BW")

p

#SED
#NMDS
nmds.asvs.h.bc <- metaMDS(asvs_subsed ,
                             distance = "bray",
                             k = 3,
                             trymax = 50,
                             autotransform = FALSE, # set to false when using normalized data from relab
                             trace = FALSE) 


nmds.seed.asvs.bc.df <- as.data.frame(nmds.asvs.h.bc$points) %>%
      rownames_to_column(var ="sample") %>%
       dplyr::rename(NMDS1 = MDS1, NMDS2 = MDS2)
 
     # check the stress plot should be a nearly linear fit
nmds.asvs.h.bc.stress <- stressplot(nmds.asvs.h.bc)


SED$temperature_set <- factor(SED$temperature_set,levels=c("Field","4","8","12","16","20","24","28","32"))

p <- nmds.seed.asvs.bc.df %>% inner_join (SED, by="sample")%>%
  ungroup()%>%
  ggplot( aes(x=NMDS1, y=NMDS2, color=as.factor(temperature_observed), shape=bay, label=samplingsite)) +
  geom_point(size = 8) +
  scale_color_manual(values=c( "cadetblue1","deepskyblue3","chartreuse3","bisque","darkorange","coral1","deeppink3","darkred"))+
  theme_bw() +
  theme(legend.position = "bottom")+
  labs(title = "SED")

p
```

```{r response taxa Phylum - Figure S9}
Bwresptax<-BW_DA %>%
  filter(!is.na(Phylum))%>%
  filter(!Phylum %in% c("Unclassified"))%>%
  group_by(Phylum,temperature_set,bay)%>%
  ungroup()%>%
  ggplot(aes(x=temperature_set, y=relab, fill=Phylum))+
  geom_bar(stat="identity", position="fill")+
  facet_grid(~bay)+
    ggtitle("Phylum")+
    theme(axis.text.x = element_text(angle = 45, hjust=1))+
    theme(legend.position="bottom")+
   scale_fill_manual(values=c("#a34641","#ff7552","#c8b087","#645436","#af9400","#f1ea00","#48c900","#0f4400","#7dc26d","#b7ffed","#016573","#000b22","#7697ff","#002690","#9781ff","#3927ce","#a78fb7","#9e0089","#f300d1","#520037","#ff70a9"))

sedresptax<-SEDresp%>%
  filter(!is.na(Phylum))%>%
  filter(!Phylum %in% c("Unclassified"))%>%
  group_by(Phylum,temperature_set,bay)%>%
  ungroup()%>%
  ggplot(aes(x=temperature_set, y=relab, fill=Phylum))+
  geom_bar(stat="identity", position="fill")+
  facet_grid(~bay)+
    ggtitle("Phylum")+
    theme(axis.text.x = element_text(angle = 45, hjust=1))+
    theme(legend.position="bottom")+
   scale_fill_manual(values=c("#a34641","#ff7552","#c8b087","#645436","#af9400","#f1ea00","#48c900","#0f4400","#7dc26d","#b7ffed","#016573","#000b22","#7697ff","#002690","#9781ff","#3927ce",
"#a78fb7","#9e0089","#f300d1","#520037","#ff70a9"))

ggarrange(Bwresptax,sedresptax, nrow=2)
```

```{r response taxa - bubble plot - Figure 6}
#BW
BW_DA <- rbind(heatedBW_DA, controlBW_DA)
Bubble_BW<- BW_DA %>%
  filter(!Genus %in% "Unclassified")%>%
 # group_by(sequence,sample,temperature_observed)%>%
    group_by(Genus,sample)%>%
  mutate(mean=mean(relab))%>%
 #top_n(10, relab)%>%
#  mutate(mean=mean(relab))%>%
  ungroup()%>%
  filter(mean >0.005)

ggplot(Bubble_SED, aes(x=temperature_set, y=Genus,size=relab, color=as.factor(bay))) +
   geom_point() +
  facet_wrap(~bay)+
     scale_size(range = c(1, 20), name="relative abundance") +
# scale_colour_gradient(low = "lightblue", high = "red")+
    theme_classic() +
     theme(legend.position="bottom") +
    ylab("Taxa") +
    xlab("temperature") 



#SED
SEDresp<- rbind(SiteB_DA, SiteD_DA, SiteF_DA, SiteK_DA, SiteL_DA, SiteM_DA )%>%
  filter(group %in% "experiment")
SEDresp$temperature_set <- factor(SEDresp$temperature_set,
                          levels = c("Field","4","8","12","16","20","24","28","32"))

###Bubble plot
Bubble_SED<- SEDresp %>%
  filter(!Genus %in% "Unclassified")%>%
 # group_by(sequence,sample,temperature_observed)%>%
    group_by(Genus,sample)%>%
  mutate(mean=mean(relab))%>%
 #top_n(10, relab)%>%
#  mutate(mean=mean(relab))%>%
  ungroup()%>%
  filter(mean >0.005)

ggplot(Bubble_SED, aes(x=temperature_set, y=Genus,size=relab, color=as.factor(bay))) +
   geom_point() +
  facet_wrap(~bay)+
     scale_size(range = c(1, 20), name="relative abundance") +
# scale_colour_gradient(low = "lightblue", high = "red")+
    theme_classic() +
     theme(legend.position="bottom") +
    ylab("Taxa") +
    xlab("temperature") 



```

